# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_picture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main.PictureImage/bytes/filename/mimetype'),
        ),
    ]
