# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160415_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['pk']},
        ),
    ]
