# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_portrait_portraitimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main.PortraitImage/bytes/filename/mimetype'),
        ),
    ]
