# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160508_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='good',
        ),
        migrations.RemoveField(
            model_name='portrait',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portrait',
            name='updated_at',
        ),
    ]
