# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160508_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portrait',
        ),
        migrations.DeleteModel(
            name='PortraitImage',
        ),
    ]
