# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160510_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='options_text',
        ),
    ]
