# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='counter',
            new_name='value',
        ),
    ]
